// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB9PXVoKwQnOpSnuhQgHvMzkSb_BNCqyg',
    appId: '1:169795872766:web:df3a4b7531feed131202af',
    messagingSenderId: '169795872766',
    projectId: 'fitconnect-be78b',
    authDomain: 'fitconnect-be78b.firebaseapp.com',
    storageBucket: 'fitconnect-be78b.appspot.com',
    measurementId: 'G-S9MHYY3KVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI86tgrvX8EHe9HFj5Urjea_-J_jtHDmM',
    appId: '1:169795872766:android:2b9fc2ac3ebdde191202af',
    messagingSenderId: '169795872766',
    projectId: 'fitconnect-be78b',
    storageBucket: 'fitconnect-be78b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhkoIAmVbfSSY1WtHecpMk7KWB64wFg6s',
    appId: '1:169795872766:ios:f276d0907a044c551202af',
    messagingSenderId: '169795872766',
    projectId: 'fitconnect-be78b',
    storageBucket: 'fitconnect-be78b.appspot.com',
    iosClientId:
        '169795872766-ou4d7noenfgqep2ap60mu0603a0dtmij.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhkoIAmVbfSSY1WtHecpMk7KWB64wFg6s',
    appId: '1:169795872766:ios:f276d0907a044c551202af',
    messagingSenderId: '169795872766',
    projectId: 'fitconnect-be78b',
    storageBucket: 'fitconnect-be78b.appspot.com',
    iosClientId:
        '169795872766-ou4d7noenfgqep2ap60mu0603a0dtmij.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitConnect',
  );
}
